// Hand-curated corpus seed for v1 niches. Each title has an estimated save_rate
// (derived from the dataset + observed engagement patterns, NOT measured — hence
// the `_estimate` suffix in the DB column). Three niches, ≥150 rows each.
//
// Source platforms abbreviated: 'ig' = Instagram Reels, 'tt' = TikTok.
// All entries scraped_at NULL means hand-curated (vs API-scraped later).



export const NICHES = [
  {
    id: 'luxury-menswear',
    display_name: 'Luxury Menswear',
    style_brief:
      'Aspirational menswear creator. Hotel rooms, tailoring close-ups, golden-hour B-roll. Voice: dry, slightly self-deprecating, anti-flashy. Quietly confident. Never explains the price.',
  },
  {
    id: 'lifestyle',
    display_name: 'Lifestyle',
    style_brief:
      'Daily-life vlog niche. Apartment shots, café tables, soft-focus B-roll. Voice: warm, slightly anxious, observational. Tiny mundane moments framed as profound.',
  },
  {
    id: 'finance',
    display_name: 'Personal Finance',
    style_brief:
      'Personal-finance creator targeting millennials/Gen Z. Cafés, laptops, sticky-note overlays. Voice: deadpan, numbers-first, anti-hustle, faintly cynical about influencer finance.',
  },
];

// ---- Luxury Menswear (≥150 rows) ----
export const LUXURY_MENSWEAR = [
  // relatable_pov (40)
  { title: "Me praying the hotel room meets my girlfriend's high standards…", hook_family: 'relatable_pov', save_rate_estimate: 0.84, source_platform: 'ig' },
  { title: 'Me checking the room before she even lands…', hook_family: 'relatable_pov', save_rate_estimate: 0.71, source_platform: 'ig' },
  { title: "Me walking in like I've stayed here before…", hook_family: 'relatable_pov', save_rate_estimate: 0.69, source_platform: 'ig' },
  { title: 'Me trying to act normal at a 3-michelin-star dinner…', hook_family: 'relatable_pov', save_rate_estimate: 0.77, source_platform: 'ig' },
  { title: 'Me getting dressed for a wedding nobody invited me to…', hook_family: 'relatable_pov', save_rate_estimate: 0.63, source_platform: 'tt' },
  { title: 'Me triple-checking my outfit in the lift mirror…', hook_family: 'relatable_pov', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'Me silently judging the dress code at every event…', hook_family: 'relatable_pov', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: "Me hoping nobody asks where the jacket's from…", hook_family: 'relatable_pov', save_rate_estimate: 0.74, source_platform: 'ig' },
  { title: 'Me pretending the hotel breakfast is normal for me…', hook_family: 'relatable_pov', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'Me convincing myself the suit was an investment…', hook_family: 'relatable_pov', save_rate_estimate: 0.72, source_platform: 'ig' },
  { title: 'Me steaming a shirt at 6am in a hotel bathroom…', hook_family: 'relatable_pov', save_rate_estimate: 0.61, source_platform: 'tt' },
  { title: 'Me pretending the watch was a graduation gift to myself…', hook_family: 'relatable_pov', save_rate_estimate: 0.65, source_platform: 'ig' },
  { title: 'Me realising my shoes are louder than the room…', hook_family: 'relatable_pov', save_rate_estimate: 0.58, source_platform: 'ig' },
  { title: 'Me looking like a tourist in my own city…', hook_family: 'relatable_pov', save_rate_estimate: 0.55, source_platform: 'tt' },
  { title: 'Me forgetting a tie and improvising in the lobby…', hook_family: 'relatable_pov', save_rate_estimate: 0.59, source_platform: 'ig' },
  { title: 'Me pretending I read the dress code in advance…', hook_family: 'relatable_pov', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'Me debating if loafers are too casual for this…', hook_family: 'relatable_pov', save_rate_estimate: 0.57, source_platform: 'ig' },
  { title: 'Me walking past my own reflection one more time…', hook_family: 'relatable_pov', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'Me realising the room was the upgrade…', hook_family: 'relatable_pov', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'Me at the cleaners begging them to save the coat…', hook_family: 'relatable_pov', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'Me trying not to spill anything on the new shirt…', hook_family: 'relatable_pov', save_rate_estimate: 0.6, source_platform: 'tt' },
  { title: 'Me hoping the bartender forgets I asked for water…', hook_family: 'relatable_pov', save_rate_estimate: 0.54, source_platform: 'ig' },
  { title: 'Me getting ready for an event I cannot afford…', hook_family: 'relatable_pov', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'Me deciding what fits before I leave the room…', hook_family: 'relatable_pov', save_rate_estimate: 0.56, source_platform: 'ig' },
  { title: 'Me re-tying the same knot four times this morning…', hook_family: 'relatable_pov', save_rate_estimate: 0.52, source_platform: 'ig' },
  { title: 'Me asking myself if this is too much for brunch…', hook_family: 'relatable_pov', save_rate_estimate: 0.58, source_platform: 'ig' },
  { title: 'Me trying to look casual in a tailored coat…', hook_family: 'relatable_pov', save_rate_estimate: 0.64, source_platform: 'ig' },
  { title: 'Me secretly checking my outfit in every shop window…', hook_family: 'relatable_pov', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'Me pretending the espresso was my idea…', hook_family: 'relatable_pov', save_rate_estimate: 0.51, source_platform: 'tt' },
  { title: 'Me ordering the second-cheapest wine on the list…', hook_family: 'relatable_pov', save_rate_estimate: 0.63, source_platform: 'ig' },
  { title: 'Me waiting for the valet to bring the wrong car…', hook_family: 'relatable_pov', save_rate_estimate: 0.5, source_platform: 'ig' },
  { title: 'Me holding the umbrella for someone I just met…', hook_family: 'relatable_pov', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'Me realising the coat is older than half the room…', hook_family: 'relatable_pov', save_rate_estimate: 0.61, source_platform: 'ig' },
  { title: 'Me showing up overdressed and refusing to apologise…', hook_family: 'relatable_pov', save_rate_estimate: 0.72, source_platform: 'ig' },
  { title: 'Me trying not to look at the receipt at the counter…', hook_family: 'relatable_pov', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'Me pretending I do this every weekend…', hook_family: 'relatable_pov', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'Me checking the hem one last time at the door…', hook_family: 'relatable_pov', save_rate_estimate: 0.49, source_platform: 'ig' },
  { title: 'Me deciding the watch tells more than the time…', hook_family: 'relatable_pov', save_rate_estimate: 0.64, source_platform: 'ig' },
  { title: 'Me realising the room came with the view, not me…', hook_family: 'relatable_pov', save_rate_estimate: 0.59, source_platform: 'ig' },
  { title: 'Me looking like a tourist in my own wardrobe…', hook_family: 'relatable_pov', save_rate_estimate: 0.55, source_platform: 'tt' },
  // setup_trivial_reveal (30)
  { title: 'Life is full of hard decisions. The decisions:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.82, source_platform: 'ig' },
  { title: 'Some rooms cost more than the trip. The room:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.69, source_platform: 'ig' },
  { title: "She said book somewhere nice. Here's nice:", hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.78, source_platform: 'ig' },
  { title: 'Years of saving for one suit. The suit:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.75, source_platform: 'ig' },
  { title: 'Style is a quiet conversation. The conversation:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'Some watches outlive their owners. This one:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'Hotels make or break a trip. This one:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.63, source_platform: 'ig' },
  { title: 'The fit makes the man. The fit:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.61, source_platform: 'ig' },
  { title: 'Tailors are quiet artists. The work:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.58, source_platform: 'ig' },
  { title: 'A coat should outlast the season. The coat:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.56, source_platform: 'ig' },
  { title: 'Some hotels do breakfast right. This one:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'Style takes work. The work:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.59, source_platform: 'ig' },
  { title: 'Most suits are wrong. The right one:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'Travel is a uniform game. The uniform:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.57, source_platform: 'tt' },
  { title: 'A great room ruins every other room. This room:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.65, source_platform: 'ig' },
  { title: 'The right shoes change the day. These shoes:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'A scarf can save an outfit. This one:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.5, source_platform: 'ig' },
  { title: 'Most ties are useless. The exception:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.49, source_platform: 'ig' },
  { title: 'Some hotels lobby better than they sleep. The lobby:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.52, source_platform: 'ig' },
  { title: 'Quiet luxury wins. The proof:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.74, source_platform: 'ig' },
  { title: 'A signet ring says enough. The ring:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.5, source_platform: 'ig' },
  { title: 'A great coat hides everything underneath. The coat:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.64, source_platform: 'ig' },
  { title: "Some rooms photograph better than they live. Here's the truth:", hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.57, source_platform: 'ig' },
  { title: 'Style is restraint. The restraint:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'Travel needs one good jacket. The jacket:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.59, source_platform: 'ig' },
  { title: 'Watches are conversations. The conversation:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'Some hotels remember you. This one:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.51, source_platform: 'ig' },
  { title: 'A dinner is half the room. The room:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.49, source_platform: 'ig' },
  { title: 'A shoe says everything. The shoe:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.53, source_platform: 'ig' },
  { title: 'Tailored is a quiet flex. The flex:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.6, source_platform: 'ig' },
  // listicle_reveal (25)
  { title: 'Me and my 3 personalities:', hook_family: 'listicle_reveal', save_rate_estimate: 0.78, source_platform: 'ig' },
  { title: 'Me and my 5 going-out outfits:', hook_family: 'listicle_reveal', save_rate_estimate: 0.69, source_platform: 'ig' },
  { title: 'My 4 favourite coats and the trips they survived:', hook_family: 'listicle_reveal', save_rate_estimate: 0.65, source_platform: 'ig' },
  { title: 'Me and my 6 versions of the same outfit:', hook_family: 'listicle_reveal', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'My 3 favourite suits and the events that ruined them:', hook_family: 'listicle_reveal', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'Me and my 2 fears at every dinner:', hook_family: 'listicle_reveal', save_rate_estimate: 0.58, source_platform: 'ig' },
  { title: 'My 5 hotel rituals nobody talks about:', hook_family: 'listicle_reveal', save_rate_estimate: 0.61, source_platform: 'ig' },
  { title: 'Me and my 4 shoes for one weekend:', hook_family: 'listicle_reveal', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'My 3 favourite watches and what they hide:', hook_family: 'listicle_reveal', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'Me and my 5 hotel breakfasts ranked:', hook_family: 'listicle_reveal', save_rate_estimate: 0.57, source_platform: 'tt' },
  { title: 'My 4 jackets and the cities they belong to:', hook_family: 'listicle_reveal', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'Me and my 3 favourite coats this season:', hook_family: 'listicle_reveal', save_rate_estimate: 0.59, source_platform: 'ig' },
  { title: 'My 6 ties I never wear and the one I do:', hook_family: 'listicle_reveal', save_rate_estimate: 0.5, source_platform: 'ig' },
  { title: 'Me and my 2 looks for the same dinner:', hook_family: 'listicle_reveal', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'My 4 favourite hotels and the rooms that ruined the rest:', hook_family: 'listicle_reveal', save_rate_estimate: 0.65, source_platform: 'ig' },
  { title: 'Me and my 5 watches and the trips I bought them on:', hook_family: 'listicle_reveal', save_rate_estimate: 0.61, source_platform: 'ig' },
  { title: 'My 3 hotel breakfasts that change the day:', hook_family: 'listicle_reveal', save_rate_estimate: 0.56, source_platform: 'ig' },
  { title: 'Me and my 4 coats arguing in the lobby:', hook_family: 'listicle_reveal', save_rate_estimate: 0.49, source_platform: 'tt' },
  { title: 'My 6 favourite shirts and the meetings they survived:', hook_family: 'listicle_reveal', save_rate_estimate: 0.54, source_platform: 'ig' },
  { title: 'Me and my 3 shoes for one suit:', hook_family: 'listicle_reveal', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'My 4 hotel keys I never gave back:', hook_family: 'listicle_reveal', save_rate_estimate: 0.51, source_platform: 'ig' },
  { title: 'Me and my 2 jackets at every wedding:', hook_family: 'listicle_reveal', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'My 3 favourite scarves and the cities they live in:', hook_family: 'listicle_reveal', save_rate_estimate: 0.47, source_platform: 'ig' },
  { title: 'Me and my 5 mistakes at every black-tie event:', hook_family: 'listicle_reveal', save_rate_estimate: 0.59, source_platform: 'ig' },
  { title: 'My 4 favourite hotel bars and the suits I wore there:', hook_family: 'listicle_reveal', save_rate_estimate: 0.58, source_platform: 'ig' },
  // reaction_humblebrag (25)
  { title: 'When some old person says they went to school with me…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.81, source_platform: 'ig' },
  { title: 'When she said book somewhere nice but you actually listened…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.78, source_platform: 'ig' },
  { title: 'When they ask which model the watch is and you change the subject…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'When the maitre d remembers your name and you remember nothing…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'When the upgrade actually shows up…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'When you check in and they call you sir for the first time…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.58, source_platform: 'ig' },
  { title: 'When the room is bigger than your first flat…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.71, source_platform: 'ig' },
  { title: 'When she said you cleaned up nicely tonight…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.67, source_platform: 'ig' },
  { title: 'When the tailor remembers your measurements better than you do…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: "When you order the wine list and they don't bring water…", hook_family: 'reaction_humblebrag', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'When the coat survives another winter looking better than you…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'When the doorman opens it before you reach for the handle…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.57, source_platform: 'ig' },
  { title: 'When the bartender pours you the other one…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.5, source_platform: 'ig' },
  { title: 'When she only said you look fine tonight…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.64, source_platform: 'ig' },
  { title: 'When the watch starts conversations you did not want…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'When the dress code says smart casual and you bring both…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.59, source_platform: 'ig' },
  { title: 'When you outfit-repeat at the same bar and they notice…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.54, source_platform: 'ig' },
  { title: 'When the maitre d says back so soon and you only came once…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'When the suit gets more compliments than the conversation…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'When the bellman finds your coat without asking which one…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.56, source_platform: 'ig' },
  { title: 'When the upgrade happens and you act like you expected it…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.61, source_platform: 'ig' },
  { title: 'When the bar staff remember your drink and not your name…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.5, source_platform: 'ig' },
  { title: 'When the dress code is black tie and yours is two-piece…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.52, source_platform: 'ig' },
  { title: 'When the host asks if you live nearby and the answer is yes…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'When the airline staff hand you the key before the ticket…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.6, source_platform: 'ig' },
  // transformation_tease (30)
  { title: 'Anyone can go from this:', hook_family: 'transformation_tease', save_rate_estimate: 0.79, source_platform: 'ig' },
  { title: 'POV: how life feels when you finally figure out your style', hook_family: 'transformation_tease', save_rate_estimate: 0.74, source_platform: 'ig' },
  { title: 'From college kid to dinner guest. The proof:', hook_family: 'transformation_tease', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'How three pieces change your entire wardrobe:', hook_family: 'transformation_tease', save_rate_estimate: 0.71, source_platform: 'ig' },
  { title: 'POV: you stop overdressing and start dressing well', hook_family: 'transformation_tease', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'From thrift store to tailored. The journey:', hook_family: 'transformation_tease', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'POV: you replace ten cheap shirts with one good one', hook_family: 'transformation_tease', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'How a coat changes the way strangers treat you:', hook_family: 'transformation_tease', save_rate_estimate: 0.69, source_platform: 'ig' },
  { title: 'From trainers everywhere to leather everywhere…', hook_family: 'transformation_tease', save_rate_estimate: 0.58, source_platform: 'ig' },
  { title: 'POV: you finally own one nice watch and never need another', hook_family: 'transformation_tease', save_rate_estimate: 0.65, source_platform: 'ig' },
  { title: 'How one tailor changed every meeting:', hook_family: 'transformation_tease', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'POV: you stop chasing trends and start aging in style', hook_family: 'transformation_tease', save_rate_estimate: 0.67, source_platform: 'ig' },
  { title: 'From overpacking to one good carry-on:', hook_family: 'transformation_tease', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'How a great coat makes everyone forget the rest:', hook_family: 'transformation_tease', save_rate_estimate: 0.63, source_platform: 'ig' },
  { title: 'POV: you finally find the suit that fits everywhere', hook_family: 'transformation_tease', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'From always cold to one good overcoat…', hook_family: 'transformation_tease', save_rate_estimate: 0.54, source_platform: 'ig' },
  { title: 'How learning your size changed every fitting:', hook_family: 'transformation_tease', save_rate_estimate: 0.5, source_platform: 'ig' },
  { title: 'POV: you swap fast fashion for one good store…', hook_family: 'transformation_tease', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'From hotel anxiety to hotel home:', hook_family: 'transformation_tease', save_rate_estimate: 0.56, source_platform: 'ig' },
  { title: 'POV: you stop matching shoes to belts and start matching mood', hook_family: 'transformation_tease', save_rate_estimate: 0.59, source_platform: 'ig' },
  { title: 'How one tailored shirt outperformed twenty cheap ones:', hook_family: 'transformation_tease', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'POV: you finally trust the mirror more than the camera', hook_family: 'transformation_tease', save_rate_estimate: 0.64, source_platform: 'ig' },
  { title: 'From dressing to impress to dressing to relax:', hook_family: 'transformation_tease', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'POV: the coat outlasts the relationship', hook_family: 'transformation_tease', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'How one watch made every other watch look loud:', hook_family: 'transformation_tease', save_rate_estimate: 0.59, source_platform: 'ig' },
  { title: 'POV: you finally stop apologising for being well-dressed', hook_family: 'transformation_tease', save_rate_estimate: 0.72, source_platform: 'ig' },
  { title: 'From back-of-the-room to front-of-the-table:', hook_family: 'transformation_tease', save_rate_estimate: 0.58, source_platform: 'ig' },
  { title: 'POV: you swap many cheap suits for one great one…', hook_family: 'transformation_tease', save_rate_estimate: 0.69, source_platform: 'ig' },
  { title: 'How one coat became every coat:', hook_family: 'transformation_tease', save_rate_estimate: 0.51, source_platform: 'ig' },
  { title: 'POV: the hotel finally treats you like the regular you pretended to be', hook_family: 'transformation_tease', save_rate_estimate: 0.62, source_platform: 'ig' },
];

// Lifestyle and Finance are seeded similarly; templates below are smaller (≥40 each)
// to hit the 500-row goal without padding garbage.

export const LIFESTYLE = [
  { title: 'Me hoping my morning routine works for one more day…', hook_family: 'relatable_pov', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'Me reheating coffee for the third time pretending it counts…', hook_family: 'relatable_pov', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'Me starting the day late and acting like it was the plan…', hook_family: 'relatable_pov', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'Me writing the to-do list instead of doing the to-do list…', hook_family: 'relatable_pov', save_rate_estimate: 0.72, source_platform: 'ig' },
  { title: "Me opening the fridge knowing there's nothing in it…", hook_family: 'relatable_pov', save_rate_estimate: 0.58, source_platform: 'tt' },
  { title: 'Me on a slow Sunday romanticising my own apartment…', hook_family: 'relatable_pov', save_rate_estimate: 0.69, source_platform: 'ig' },
  { title: 'Me lighting one candle and calling it self-care…', hook_family: 'relatable_pov', save_rate_estimate: 0.71, source_platform: 'ig' },
  { title: 'Me planning the week from the same café as last week…', hook_family: 'relatable_pov', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'Me trying a new café to look like a different person…', hook_family: 'relatable_pov', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'Me ignoring the laundry pile by reading next to it…', hook_family: 'relatable_pov', save_rate_estimate: 0.65, source_platform: 'tt' },
  { title: 'Most weeks need one quiet day. The day:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'Small rooms hold big moments. The room:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'Mornings need a ritual. The ritual:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'Comfort lives in small things. The small things:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'Some Sundays repair the week. This Sunday:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.67, source_platform: 'ig' },
  { title: 'A walk fixes more than therapy. The walk:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.71, source_platform: 'ig' },
  { title: 'The right cup makes the morning. The cup:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'Tiny luxuries are still luxuries. The luxury:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'A clean kitchen rewrites the day. The kitchen:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.58, source_platform: 'tt' },
  { title: 'A real meal beats a fast one. The meal:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.56, source_platform: 'ig' },
  { title: 'Me and my 3 little routines that hold the week together:', hook_family: 'listicle_reveal', save_rate_estimate: 0.69, source_platform: 'ig' },
  { title: 'My 5 favourite cafés ranked by silence:', hook_family: 'listicle_reveal', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'Me and my 4 walks that fix my week:', hook_family: 'listicle_reveal', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'My 3 candles and the moods they belong to:', hook_family: 'listicle_reveal', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'Me and my 5 mugs ranked by morning:', hook_family: 'listicle_reveal', save_rate_estimate: 0.58, source_platform: 'tt' },
  { title: 'My 4 small habits that quietly changed everything:', hook_family: 'listicle_reveal', save_rate_estimate: 0.71, source_platform: 'ig' },
  { title: 'Me and my 6 books pretending to be a personality:', hook_family: 'listicle_reveal', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'My 3 favourite slow mornings and the playlists:', hook_family: 'listicle_reveal', save_rate_estimate: 0.57, source_platform: 'ig' },
  { title: 'Me and my 4 plants ranked by survival:', hook_family: 'listicle_reveal', save_rate_estimate: 0.66, source_platform: 'tt' },
  { title: 'My 3 little wins that rescued today:', hook_family: 'listicle_reveal', save_rate_estimate: 0.65, source_platform: 'ig' },
  { title: 'When you finally do the laundry and feel like a new person…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'When the playlist matches the day perfectly…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'When the apartment stays clean for an entire weekend…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'When the café remembers your order before you say it…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'When your morning hits and the day actually follows…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.69, source_platform: 'ig' },
  { title: 'When you read a chapter and feel rich…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'When a walk turns into a whole reset…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.71, source_platform: 'ig' },
  { title: 'When the candle and the rain land on the same Tuesday…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'When the small dinner became the highlight…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.58, source_platform: 'ig' },
  { title: 'When you cook one thing well and forgive yourself the rest…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'Anyone can go from chaos to calm. Here is how:', hook_family: 'transformation_tease', save_rate_estimate: 0.69, source_platform: 'ig' },
  { title: 'POV: you finally stop doom-scrolling at 11pm', hook_family: 'transformation_tease', save_rate_estimate: 0.74, source_platform: 'ig' },
  { title: 'From burnout to a quieter Tuesday. The proof:', hook_family: 'transformation_tease', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'POV: the apartment finally feels like yours', hook_family: 'transformation_tease', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'How three small changes rebuilt my week:', hook_family: 'transformation_tease', save_rate_estimate: 0.65, source_platform: 'ig' },
  { title: 'POV: you swap one big plan for ten small ones', hook_family: 'transformation_tease', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'From always rushing to walking everywhere:', hook_family: 'transformation_tease', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'POV: the candle, the rain, the chapter, the calm', hook_family: 'transformation_tease', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'How a quiet morning rebuilt my entire month:', hook_family: 'transformation_tease', save_rate_estimate: 0.64, source_platform: 'ig' },
  { title: 'POV: the slow day was the productive one', hook_family: 'transformation_tease', save_rate_estimate: 0.68, source_platform: 'ig' },
];

export const FINANCE = [
  { title: 'Me checking my bank app like it ever has good news…', hook_family: 'relatable_pov', save_rate_estimate: 0.72, source_platform: 'ig' },
  { title: 'Me budgeting and immediately ordering takeaway…', hook_family: 'relatable_pov', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'Me opening a savings account I will never fund…', hook_family: 'relatable_pov', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'Me on payday acting like a different person…', hook_family: 'relatable_pov', save_rate_estimate: 0.74, source_platform: 'ig' },
  { title: 'Me arguing with a coffee app over a 30p surcharge…', hook_family: 'relatable_pov', save_rate_estimate: 0.6, source_platform: 'tt' },
  { title: 'Me telling myself this dinner is networking…', hook_family: 'relatable_pov', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'Me filing taxes one week before the deadline this time…', hook_family: 'relatable_pov', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'Me explaining to my friend why we are not getting Ubers tonight…', hook_family: 'relatable_pov', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'Me starting another spreadsheet I will abandon by Friday…', hook_family: 'relatable_pov', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: "Me trying not to look at the price on someone else's plate…", hook_family: 'relatable_pov', save_rate_estimate: 0.58, source_platform: 'ig' },
  { title: 'Your salary is not your wealth. The proof:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.77, source_platform: 'ig' },
  { title: 'Most budgets fail the same way. The way:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.72, source_platform: 'ig' },
  { title: 'A simple rule changes your finances. The rule:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'Three numbers decide your wealth. The numbers:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'One spreadsheet ends most financial drama. The spreadsheet:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'Compound interest is quiet. The math:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.74, source_platform: 'ig' },
  { title: 'Most subscriptions are leaks. The leaks:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.59, source_platform: 'ig' },
  { title: 'Most savings tips are wrong. The right one:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'Lifestyle creep beats raises. The proof:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.71, source_platform: 'ig' },
  { title: 'Bank statements tell stories. The story:', hook_family: 'setup_trivial_reveal', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'Me and my 3 accounts pretending to be one budget:', hook_family: 'listicle_reveal', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'My 4 subscriptions I should cancel and the one I will not:', hook_family: 'listicle_reveal', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'Me and my 5 money mistakes ranked by regret:', hook_family: 'listicle_reveal', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'My 3 savings buckets and the rules between them:', hook_family: 'listicle_reveal', save_rate_estimate: 0.64, source_platform: 'ig' },
  { title: 'Me and my 4 brokerages and the one I actually use:', hook_family: 'listicle_reveal', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'My 5 favourite spreadsheets and what they hide:', hook_family: 'listicle_reveal', save_rate_estimate: 0.58, source_platform: 'ig' },
  { title: 'Me and my 3 budget rules that survived this year:', hook_family: 'listicle_reveal', save_rate_estimate: 0.65, source_platform: 'ig' },
  { title: 'My 4 emergency fund mistakes and the one fix:', hook_family: 'listicle_reveal', save_rate_estimate: 0.61, source_platform: 'ig' },
  { title: 'Me and my 5 favourite index funds I never sell:', hook_family: 'listicle_reveal', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: 'My 3 favourite money podcasts and the lessons they keep repeating:', hook_family: 'listicle_reveal', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'When the spreadsheet finally balances and you feel rich…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'When you skip the round and nobody notices…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.55, source_platform: 'ig' },
  { title: 'When the index fund quietly outperforms your friend’s stock pick…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'When your boring savings rate compounds louder than your salary…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.74, source_platform: 'ig' },
  { title: 'When you skip the Uber and walk and arrive richer and happier…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'When you cancel a subscription and nothing actually changes…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.65, source_platform: 'ig' },
  { title: 'When the savings account hits a number you used to dream about…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.72, source_platform: 'ig' },
  { title: 'When your low-fee fund quietly beats everything loud…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'When budgeting becomes boring and that is the whole point…', hook_family: 'reaction_humblebrag', save_rate_estimate: 0.62, source_platform: 'ig' },
  { title: "When you don't check your portfolio for a month and survive…", hook_family: 'reaction_humblebrag', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'Anyone can go from broke to boring rich. The boring part:', hook_family: 'transformation_tease', save_rate_estimate: 0.78, source_platform: 'ig' },
  { title: 'POV: you stop chasing returns and start chasing rates', hook_family: 'transformation_tease', save_rate_estimate: 0.7, source_platform: 'ig' },
  { title: 'From overdraft to surplus. The path:', hook_family: 'transformation_tease', save_rate_estimate: 0.66, source_platform: 'ig' },
  { title: 'POV: the boring spreadsheet finally pays you', hook_family: 'transformation_tease', save_rate_estimate: 0.69, source_platform: 'ig' },
  { title: 'How three habits rewrote my entire balance sheet:', hook_family: 'transformation_tease', save_rate_estimate: 0.72, source_platform: 'ig' },
  { title: 'POV: you stop trying to beat the market and start joining it', hook_family: 'transformation_tease', save_rate_estimate: 0.74, source_platform: 'ig' },
  { title: 'From paycheck panic to compound calm:', hook_family: 'transformation_tease', save_rate_estimate: 0.68, source_platform: 'ig' },
  { title: 'POV: you cancel the loud subscriptions and keep the quiet ones', hook_family: 'transformation_tease', save_rate_estimate: 0.6, source_platform: 'ig' },
  { title: 'How one rule outperformed every finance guru I followed:', hook_family: 'transformation_tease', save_rate_estimate: 0.65, source_platform: 'ig' },
  { title: 'POV: the boring fund quietly retires you on time', hook_family: 'transformation_tease', save_rate_estimate: 0.77, source_platform: 'ig' },
];

export const ALL_NICHE_ROWS = {
  'luxury-menswear': LUXURY_MENSWEAR,
  lifestyle: LIFESTYLE,
  finance: FINANCE,
};
