-- Description-space retrieval + real performance metrics.
-- Idempotent, like 0001. Run via `supabase db push`.
--
-- WHY THIS EXISTS
--
-- Retrieval compared the wrong two things. The query side (orchestrator.ts)
-- embeds a description of the uploaded video; the corpus side embedded the
-- TITLE text. Cosine similarity between a scene description and a punchy hook
-- line is close to noise, so retrieval was only weakly better than random.
--
-- The fix is description <-> description matching. Corpus descriptions were
-- generated by scripts/describe-videos.ts reproducing the app's runtime vision
-- call byte-for-byte (same prompt, same model, same 8-frame sampling), so both
-- sides land in the same embedding space and are directly comparable.
--
-- TWO embedding columns are required, not one replacement:
--   description_embedding -> relevance ("which corpus videos look like this?")
--   embedding (title)     -> MMR diversity and computeTitlePrior
-- MMR must spread the 8 chosen examples apart as TITLES. Running it on
-- description vectors could return eight different scenes whose hooks are all
-- phrased identically, which is the opposite of useful for few-shot prompting.

-- 1. save_rate_estimate -> performance_score
--
-- Saves are unobtainable: Apify exposes no field, SocialCrawl returns null on
-- every reel including its premium endpoint, and Instagram now hides the
-- feature. The column holds the percentile rank of share_rate instead. Leaving
-- the old name invites exactly the misreading that caused this investigation.
-- See docs/findings/2026-08-02-performance-metric-decision.md.

do $$
begin
  if exists (
        select 1 from information_schema.columns
         where table_schema = 'public' and table_name = 'corpus_titles'
           and column_name = 'save_rate_estimate')
     and not exists (
        select 1 from information_schema.columns
         where table_schema = 'public' and table_name = 'corpus_titles'
           and column_name = 'performance_score')
  then
    alter table corpus_titles rename column save_rate_estimate to performance_score;
  end if;
end $$;

-- 2. New columns.
--
-- share_rate_estimate already exists from 0001 and was never populated; it now
-- holds the raw share_rate that performance_score is the percentile of, so the
-- score can be re-derived without a re-scrape. The name is finally accurate.

alter table corpus_titles
  add column if not exists visual_description    text,
  add column if not exists description_embedding extensions.vector(1536),
  add column if not exists view_outlier_score    real,
  add column if not exists title_template        text,
  add column if not exists creator_handle        text;

comment on column corpus_titles.performance_score is
  'Percentile rank (0-1) of share_rate across the corpus. NULL means unmeasured, NOT zero — a zero would rank an unmeasured title at the bottom and teach the model it failed.';
comment on column corpus_titles.view_outlier_score is
  'Percentile rank (0-1) of views / creator median. Stored for the eval to compare against performance_score; not yet consumed at runtime.';
comment on column corpus_titles.description_embedding is
  'Embedding of visual_description. Retrieval ranks on THIS; `embedding` stays title-space for MMR and computeTitlePrior.';
comment on column corpus_titles.creator_handle is
  'Distinguishes the subject creator''s own titles from B-roll reference creators.';

-- Percentiles are corpus-relative: adding rows later invalidates every existing
-- score. Recompute the whole corpus and re-import; never append rows carrying
-- stale percentiles.

create index if not exists corpus_titles_creator_idx
  on corpus_titles (niche_id, creator_handle);

-- 3. Rebuild the retrieval RPC.
--
-- Dropped rather than replaced because the returns-table signature changes,
-- and `create or replace function` cannot alter OUT parameters.

drop function if exists match_corpus_titles(text, extensions.vector(1536), int);

create function match_corpus_titles(
  p_niche_id      text,
  p_query_embed   extensions.vector(1536),
  p_match_limit   int default 30
)
returns table (
  id                  uuid,
  title               text,
  hook_family         text,
  performance_score   real,
  view_outlier_score  real,
  creator_handle      text,
  visual_description  text,
  embedding           extensions.vector(1536),
  similarity          real
)
language sql
stable
as $$
  select
    c.id,
    c.title,
    c.hook_family,
    c.performance_score,
    c.view_outlier_score,
    c.creator_handle,
    c.visual_description,
    -- TITLE-space vector, deliberately: consumed by mmrRerank and
    -- computeTitlePrior, neither of which wants description similarity.
    c.embedding,
    (1 - (c.description_embedding <=> p_query_embed))::real as similarity
  from corpus_titles c
  where c.niche_id = p_niche_id
    and c.description_embedding is not null
    and c.embedding is not null
  order by c.description_embedding <=> p_query_embed
  limit p_match_limit;
$$;

-- Rows without a description_embedding are excluded by the WHERE clause, so
-- the 250 hand-invented seed titles from seed/corpus.mjs cannot reach
-- retrieval even if they are still present. Note the corollary: any niche
-- without imported descriptions (lifestyle, finance) now returns zero rows.
-- The niche selector (deliverable 5) must import real data per niche first.
--
-- Still no ivfflat index — sequential scan wins below ~10k rows (see 0001).

grant execute on function match_corpus_titles(text, extensions.vector(1536), int) to service_role;
